apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: testing-react-app
  labels:
    app.kubernetes.io/name: testing-react-app
    app.kubernetes.io/part-of: testing-react-app-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: testing-react-app