apiVersion: v1
kind: Service
metadata:
  name: testing-react-app
  namespace: dev
  labels:
    app.kubernetes.io/name: testing-react-app
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: testing-react-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000