import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import "@/app/styles/globals.css";
import Footer from "./(common)/footer";
import { Toaster } from "@/components/ui/sonner";
import Header from "./(common)/header";
import ScrollToTop from "./(common)/scroll-to-top";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="relative">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
        {/* Toast */}
        <Toaster richColors position="top-right" />
        {/* Scroll to Top Button */}
        <ScrollToTop />
      </body>
    </html>
  );
}
