name: Build and Push to Azure Container Registry

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.ACR_ENDPOINT }}/safesolution-portfolio-prod:latest
          file: ./Dockerfile
          build-args: |
            "VITE_API_URL=${{ secrets.VITE_API_URL }}"
            "VITE_API_TOKEN=${{ secrets.VITE_API_TOKEN }}"
