name: Build and Push to Azure Container Registry

on:
  push:
    branches:
      - "main"
      - "staging"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      # Set environment-specific variables
      - name: Set Environment Variables
        id: set-env
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "IMAGE_TAG=prod-latest" >> $GITHUB_ENV           
          elif [ "${{ github.ref }}" = "refs/heads/staging" ]; then
            echo "IMAGE_TAG=staging-latest" >> $GITHUB_ENV          
          fi

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.ACR_ENDPOINT }}/safesolution-portfolio:${{ env.IMAGE_TAG }}
          file: ./Dockerfile
          secrets: |
            "next_public_tinymce_api_url=${{ secrets.NEXT_PUBLIC_TINYMCE_API_URL }}"
            "database_url=${{ secrets.DATABASE_URL }}"         
            "better_auth_secret=${{ secrets.BETTER_AUTH_SECRET }}"
            "mail_from_address=${{ secrets.MAIL_FROM_ADDRESS }}"
            "mail_from_name=${{ secrets.MAIL_FROM_NAME }}"
            "mail_host=${{ secrets.MAIL_HOST }}"
            "mail_password=${{ secrets.MAIL_PASSWORD }}"
            "mail_port=${{ secrets.MAIL_PORT }}"
            "mail_username=${{ secrets.MAIL_USERNAME }}"
