# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - safesolution-portfolio-staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://portalfront.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_df1554662ff040e8853f0250f6f20df7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5752d87b383c42d09f21d395348d7551 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: portalfront.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_df1554662ff040e8853f0250f6f20df7 }}/safesolution-stag-image:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'safesolution-portfolio-staging'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f7c6c45f19684d9ca0a756b6cee98760 }}
        images: 'portalfront.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_df1554662ff040e8853f0250f6f20df7 }}/safesolution-stag-image:${{ github.sha }}'